server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IhorMurashko/cloud-config.git
          username: username
          password: password
          default-label: main
          search-paths: "{application}"