# YAML configuration file for the Clients Application

# Sets the server port for the Clients application
server:
  port: 8081  # Clients application will run on port 8081

spring:
  application:
    # Application name identifier for the Clients service
    name: clients

  config:
    # Specifies that the application will import configuration properties
    # from a Config Server running at the given URL
    import: configserver:http://localhost:8888  # URL of the Config Server
